### ISSUE TITLE
[BUG] Posts in PUG: "you are not in a party" (in german)

### ISSUE THREAD

**Issue by Kimab** [Davie3/who-taunted#12]
Hey :) first time doing a bug report, sorry for my bad english explanation :P
if you need anything else, let me know

**WoW Client Version**
10.0.0.46313

**Lua Error**
No error, just the message

**Describe the bug**
Joining a PUG brings me 3-8 times the message "you are not in a party" and sometimes while doing the pug. as far as i can say its only in random pugs, so NOT in m+ groups.
the messages also appear if someone leave the group. not every time, but now and then

**To Reproduce**
activiate the addon and join a random group, random heroic oder normal dungeon works both

**Expected behavior**
not getting these chat messages

**Screenshots**
if you want, you can have... its just the yellow blizzard text saying multiple times im not in a group (in german)

**Additional context**
i think it started with the update on version 2.0.1, Oct 4th 2022

**Comment by Davie3** [comment]
Thanks for the report! I might know why that is happening and I'll look into it.

**Comment by Kimab** [comment]
thanks for the fast response! looking forward to an update :) i also did some work on the translations, i hope they are okay for my german speaking friends :D

**Comment by Davie3** [comment]
@Kimab Thank you for the report! This should be fixed in v2.0.3! You can download the updated version from Curesforge - https://www.curseforge.com/wow/addons/who-taunted/files/4053235

Feel free to reopen this issue if it still comes up!

**Comment by Kimab** [comment]
Thank you for updating it this fast!
