### ISSUE TITLE
[BUG] not able so set Taunt warnings

### ISSUE THREAD

**Issue by Nemesis2354** [Davie3/who-taunted#15]
**WoW Client Version**
10.00

**Lua Error**
Not a Lua Error

**Describe the bug**
it is not possible to set the warning in the options menu. The setting is empty and can not be filled

**To Reproduce**
Yes it can be reproduced
![WoWScrnShot_110722_171403](https://user-images.githubusercontent.com/72879850/200359543-9b837cfe-8c93-43c9-97a5-efae777b1381.jpg)

**Expected behavior**
If applicable, what did you expect to happen?

**Screenshots**

**Additional context**

**Comment by Davie3** [comment]
Thanks for the report! This might be a localization bug. I will look into it!

**Comment by Davie3** [comment]
I was able to reproduce the bug while on the Deutsch local. I'll try to get a fix out this weekend!

**Comment by Nemesis2354** [comment]
Thank you very much for your work. At the moment, this Addon is useless in german WoW Versions, because there are no taunts warnings possible

**Comment by Davie3** [comment]
@Nemesis2354 Thank you for the report! This should be fixed in v2.0.4! You can download the updated version from Curesforge - https://www.curseforge.com/wow/addons/who-taunted/files/4077638

Feel free to reopen this issue if it still comes up!
