### ISSUE TITLE
9.0.1 support?

### ISSUE THREAD

**Issue by scalp42** [Davie3/who-taunted#2]
Hi @Davie3 

Curious if you had any plans for 9.0.1 support (prepatch)?

Thanks in advance

**Comment by Davie3** [comment]
Hi @scalp42 !

Yes, definitely! I haven't been playing WoW much lately so will use 9.0.1 as an excuse to come back.

Will definitely get this addon updated ASAP!

**Comment by Davie3** [comment]
v1.5 has been released!

https://www.curseforge.com/wow/addons/who-taunted/files

**Comment by scalp42** [comment]
You rock!
