### ISSUE TITLE
Anouncements not getting send to configured chat.

### ISSUE THREAD

**Issue by HelgeBecker** [Davie3/who-taunted#54]
As the title says.
The announcements are supposed to go to a specific chat window, where I can see them. Worked fine till the release of TWW.
Not working since then. Deinstalling and wiping its settings didn't help.

**Comment by HelgeBecker** [comment]
Last Wednesday who-tauntet startet to work again partly.. The addon uses the correct chat, but it does not keep the setting. Not sure if this is a Blizzard issue.

**Comment by Davie3** [comment]
Sorry for the delay. I'll be renewing my subscription for the WoW anniversary.

Thanks for the report. I'll try to get a fix for the next compatibility release or the release after.

**Comment by Davie3** [comment]
This should be fixed in v2.1.3.

**Comment by HelgeBecker** [comment]
It is. Thank you 😍
