### ISSUE TITLE
[BUG] Announcements settings don't save upon relogging

### ISSUE THREAD

**Issue by RealHawkBat** [Davie3/who-taunted#55]
**WoW Client Version**
Retail 11.0.2 (56819)(Release x64)
**Lua Error**
N/A

**Describe the Bug**
In the "Announcements" section of the Options, if I change the "Chat Window" option, it doesn't save after relogging.

**Steps to Reproduce**
1. Go to Options for Who Taunted?
2. Go to "Annoucements" section
3. In the "Chat Window" drop down, change it from "General" to another chat window
4. Log out of WoW
5. Log back into WoW

**Expected Behavior**
Upon logging into WoW, the "Chat Window" drop down should still have whatever channel I had selected, selected.

**Actual Behavior**
Upon logging into WoW, the "Chat Window" drop down has "General" selected again

**Screenshots**
N/A

**Additional Context**
N/A

**Comment by Davie3** [comment]
Thanks for the report. I'll try to get a fix for the next compatibility release or the release after.
